#pragma once
#include <devioctl.h>

#define IOCTL_DISABLE_DEEPFRZ CTL_CODE(FILE_DEVICE_UNKNOWN,0x1,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IOCTL_REBOOT_SYSTEM   CTL_CODE(FILE_DEVICE_UNKNOWN,0x2,METHOD_BUFFERED,FILE_ANY_ACCESS)